homeassistant:
  # 家庭名称
  name: Home
  # 所在地经纬度
  latitude: 31.286571
  longitude: 121.130073
  # 海拔高度
  elevation: 0
  # 公制: metric, 英制: imperial
  unit_system: metric
  # 所在时区
  time_zone: Asia/Shanghai
  # 自定义文件
  customize: !include customize.yaml
  packages: !include_dir_named packages

# 默认设置(frontend, api...)
default_config:

# 启动欢迎语
introduction:

# 自定义面板
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'http://home.wannayoung.top:1880/'

# 使用Custom-UI
frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

# 文字转语音
tts:
  - platform: google

# homekit配置
homekit: 

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
